action_id: trunk-upgrade-available
date: 2025-04-17 10:36:48
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-upgrade-available'. See .trunk\out\u0DaB.yaml for details.
  error_path: D:\box\ODSLY\ODSLY\.trunk\out\u0DaB.yaml
timestamp: 1744886208
full_timestamp:
  nanos: 159691000
  seconds: 1744886208
trunk_version: 1.22.12
